# Generated by Django 5.2.6 on 2026-03-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_table',
            name='date',
            field=models.DateField(),
        ),
    ]
