# Generated by Django 5.2.6 on 2026-03-09 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_request_table_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill_reminder_table',
            name='USER',
        ),
        migrations.AddField(
            model_name='pill_reminder_table',
            name='CARETAKER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.caretaker_table'),
        ),
        migrations.AddField(
            model_name='pill_reminder_table',
            name='PATIENT',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.patients_table'),
        ),
    ]
