# Generated by Django 5.2.6 on 2026-03-09 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_pill_reminder_table_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill_reminder_table',
            name='PATIENT',
        ),
        migrations.AddField(
            model_name='pill_reminder_table',
            name='ASSIGNED',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.assigned_caretaker_table'),
        ),
    ]
