# Generated by Django 5.2.6 on 2026-03-14 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_pill_reminder_table_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fall_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=15)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patients_table')),
            ],
        ),
    ]
