# Generated by Django 5.2.12 on 2026-03-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_fall_notification_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review_table',
            new_name='review_tabale',
        ),
    ]
